### PR TITLE
Fix event update

### PR DESCRIPTION
**Pull request by ip**
Previous code didn't work correctly when event listener is a closure and it is replaced by a similar clojure with different enclosed variables.

May be related to the issue #89.

### CODE REVIEW

**Comment by ngokevin** [comment]
Thanks! Can we get a unit test that reproduces?

**Comment by ip** [comment]
All right, I'll make it later

**Comment by ip** [comment]
Sorry, unit test is postponed, have no time at the moment. Any help is appreciated.

**Comment by ip** [comment]
By the way, your unit test config is interesting. I want to use parts of it for our project, ones that mock WebGL and allow headless run.

**Comment by ip** [comment]
Just have a look at this snippet: https://jsbin.com/widupebula/edit?js,console

**Comment by ngokevin** [comment]
Yeah, it just stubs out any WebGL renderer so you can assert JS stuff.

**Pull request merged**
